### PR TITLE
Remove eqn_of_state from generic tracer interface 

### PR DESCRIPTION
**Pull request by theresa-cordero**
Remove eqn_of_state from generic tracer interfaces and from COBALT code.

### CODE REVIEW

**Review by yichengt900 — APPROVED** [review]

**Comment by theresa-cordero** [comment]
@yichengt900 At the COBALT meeting yesterday we also discussed wanting to merge PR 93 first so the parameters and photoacclimation MLD code used in Charlie's paper are both present in one version of COBALT. This is mostly for future users who want to understand the calculations and parameters used in that paper.

**Comment by yichengt900** [comment]
@theresa-morrison, thanks for the note. Sounds good to me. I will merge PR93 first, and we can address the rest of the PRs later. Also, feel free to create a separate PR to handle the unit conversion issue when there's a chance.

**Comment by charliestock** [comment]
Hi @yichengt900, @theresa-morrison, this pull request looks good to me.  Shall we pull it in?

**Comment by yichengt900** [comment]
@charliestock , this is on my to-do list. Given that this PR, along with the related MOM6 PR, will affect all of our experiments, I want to ensure I allocate sufficient time to update everything at once, including the XMLs, to minimize any disruption.

On a positive note, we've resolved the C6/F6 data archiving issue causing by the FRE/bronx-22, and the XMLs for the global OM4 configurations (0.5, 0.25, and 0.125deg) with COBALTv3 are nearly complete. I aim to merge this PR and finalize all updates by the end of this week.

**Comment by charliestock** [comment]
Sounds great Yi-Cheng - thank you for all of your efforts!  I'm going to try and knock off a few more parameter definitions in the next few days.  I'll just be sure to synchronize with the current code when I make a pull request.

**Pull request merged**
