### PR TITLE
Change COBALT bottom fluxes from 3d array to 2d

### PR DESCRIPTION
**Pull request by yichengt900**
This PR resolves issue #38 by converting the COBALT bottom fluxes array from 3D to 2D, enhancing memory efficiency.
this PR is solely for code refactoring and does not alter the modeled results.

### CODE REVIEW

**Review by andrew-c-ross — APPROVED** [review]
At first I was surprised that this works, since the vertdiff routine uses %btf, but then I remembered vertdiff only gets applied to prognostic tracers and these are all diagnostic tracers, so this checks out :+1: 

The only side effect I can see is that enabling the bottom flux automatically creates potentially confusing diagnostics with names like "lithdet_btf_btf".

**Comment by yichengt900** [comment]
@andrew-c-ross, thank you. Regarding the side effects, perhaps we could consider renaming those diagnostics? For example, renaming `cadet_arag_btf` to` b_cadet_arag` to avoid confusion. What are your thoughts?

**Comment by andrew-c-ross** [comment]
> Regarding the side effects, perhaps we could consider renaming those diagnostics? For example, renaming `cadet_arag_btf` to` b_cadet_arag` to avoid confusion. 

I think it's fine to leave everything as is. The *_btf_btf diagnostic only appears if you look for it in the available_diags file.

**Comment by andrew-c-ross** [comment]
I looked at one of my older runs, for other variables that have a bottom flux, I don't see that bottom flux saved in the restarts (for example, I don't see no3_btf in the restarts). This could confirm Charlie's suspicion that the new diagnostic _btfs aren't being saved in the restarts.

**Pull request merged**
