### PR TITLE
cleanup phytoplankton uptake section

### PR DESCRIPTION
**Pull request by charliestock**
This pull request just cleans up the uptake code and adds a few comments.  I have also suggested removing the diagnostic "net_phyto_resp", which we don't really use for anything and can be easily calculated from the growth rate.   We should check to ensure this is not in our standard diagnostic tables.

These changes should not change answers.

### CODE REVIEW

**Comment by yichengt900** [comment]
@charliestock , by checking our current [NWA12 diag_table](https://github.com/NOAA-GFDL/CEFI-regional-MOM6/blob/1d799141b6842b04d11d38abbcfde129894c7ef2/xmls/NWA12/diag_tables/diag_table_COBALT_2023-04#L290), we do output water column integrated net_phyto_resp.

**Review by yichengt900 — COMMENTED** [review]
If we want to remove `net_phyto_resp`. We will also have to remove the following diagnostic lines in `cobalt_send_diag.F90`:

https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/96914377095b78dc271fd908ca5bddc34ebfcb04/generic_tracers/cobalt_send_diag.F90#L331-L333

https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/96914377095b78dc271fd908ca5bddc34ebfcb04/generic_tracers/cobalt_send_diag.F90#L1175-L1176

**Comment by charliestock** [comment]
I think net_phyto_resp and wc_net_phyto_resp have now been successfully removed from the code.  I have also confirmed that it is indeed redundant with other diagnostics.  The only thing that we'll need to ensure is that the diagnostic "wc_net_phyto_resp" is removed from all of our diagnostic tables.

**Review by yichengt900 — APPROVED** [review]
Changes looks good, @charliestock , I also used this change to fix #55. Approve.

**Pull request merged**
