### PR TITLE
Recalibrate calcite and aragonite detritus flux

### PR DESCRIPTION
**Pull request by feida6996**
This addresses discussion point https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/issues/36 by adjusting the production rates of calcite and aragonite detritus (PIC). 

We found that the current PIC flux at 100 m in COBALTv3, especially calcite, is too low compared to literature values. Recent studies ([Sulpis et al. 2021](https://www.nature.com/articles/s41561-021-00743-y); [Neukermans et al. 2023](https://www.sciencedirect.com/science/article/pii/S001282522300048X?via%3Dihub)) suggest that PIC export ranges from 0.4-1.8 Pg C y-1, with a mean of ~0.9 to 1.0 Pg C y-1.

At the global scale, we recalibrated two constants (ca_2_n_arag and ca_2_n_calc) to achieve the targeted PIC flux of 0.9 Pg C y-1 at a depth of 100 m, with a calcite and aragonite flux ratio of approximately 3:1.

Here is the result showing the global calcite and aragonite flux at 100m under pre-industrial atmospheric CO2 levels.
Picture2

@yichengt900 @charliestock

### CODE REVIEW

**Comment by yichengt900** [comment]
@feida6996, thank you! I am glad to see that the flux looks better after recalibration. I have no problem with this change, but as @charliestock suggested, I will conduct a short-term regional run to ensure that the surface DIC/ALK still look good.

**Comment by yichengt900** [comment]
BTW, @feida6996  below are the new answers. Please replace your existing answers with this one when you have change:
```
  Step,       Day,  Truncs,      Energy/Mass,      Maximum CFL,  Mean Sea Level,  Total Mass,  Mean Salin, Mean Temp, Frac Mass Err,   Salin Err,    Temp Err
            [days]                 [m2 s-2]           [Nondim]       [m]             [kg]         [PSU]      [degC]       [Nondim]        [PSU]        [degC]
     0,  731595.000,     0, En 4.0531850015098383E-27, CFL  0.00000, SL -0.0000E+00, M 6.97073E+15, S 35.2427, T  6.2462, Me  0.00E+00, Se  0.00E+00, Te  0.00E+00
     6,  731595.250,     0, En 2.0223578954766472E-06, CFL  0.00281, SL -3.4291E-06, M 6.97073E+15, S 35.2427, T  6.2460, Me -8.57E-10, Se -2.85E-07, Te -2.66E-06
    12,  731595.500,     0, En 4.2897044161040916E-06, CFL  0.00294, SL -6.4127E-06, M 6.97073E+15, S 35.2427, T  6.2457, Me -7.46E-10, Se -6.81E-07, Te -6.81E-06
    18,  731595.750,     0, En 1.2185516095946735E-05, CFL  0.00794, SL -9.2141E-06, M 6.97073E+15, S 35.2427, T  6.2459, Me -7.00E-10, Se -9.89E-07, Te -1.00E-05
    24,  731596.000,     0, En 2.4391883408641453E-05, CFL  0.00870, SL -1.3774E-05, M 6.97073E+15, S 35.2427, T  6.2457, Me -1.14E-09, Se -1.40E-06, Te -1.42E-05
    30,  731596.250,     0, En 2.9283640487163710E-05, CFL  0.00724, SL -1.8458E-05, M 6.97073E+15, S 35.2427, T  6.2454, Me -1.17E-09, Se -1.93E-06, Te -1.96E-05
    36,  731596.500,     0, En 3.6652617800868474E-05, CFL  0.00746, SL -2.3211E-05, M 6.97073E+15, S 35.2427, T  6.2451, Me -1.19E-09, Se -2.37E-06, Te -2.42E-05
    42,  731596.750,     0, En 4.2253748371831278E-05, CFL  0.00812, SL -2.7653E-05, M 6.97073E+15, S 35.2427, T  6.2454, Me -1.11E-09, Se -2.79E-06, Te -2.86E-05
    48,  731597.000,     0, En 4.7781350107303387E-05, CFL  0.00941, SL -3.1143E-05, M 6.97073E+15, S 35.2427, T  6.2453, Me -8.73E-10, Se -3.05E-06, Te -3.14E-05
```

**Comment by feida6996** [comment]
> BTW, @feida6996 below are the new answers. Please replace your existing answers with this one when you have change:
> 
> ```
>   Step,       Day,  Truncs,      Energy/Mass,      Maximum CFL,  Mean Sea Level,  Total Mass,  Mean Salin, Mean Temp, Frac Mass Err,   Salin Err,    Temp Err
>             [days]                 [m2 s-2]           [Nondim]       [m]             [kg]         [PSU]      [degC]       [Nondim]        [PSU]        [degC]
>      0,  731595.000,     0, En 4.0531850015098383E-27, CFL  0.00000, SL -0.0000E+00, M 6.97073E+15, S 35.2427, T  6.2462, Me  0.00E+00, Se  0.00E+00, Te  0.00E+00
>      6,  731595.250,     0, En 2.0223578954766472E-06, CFL  0.00281, SL -3.4291E-06, M 6.97073E+15, S 35.2427, T  6.2460, Me -8.57E-10, Se -2.85E-07, Te -2.66E-06
>     12,  731595.500,     0, En 4.2897044161040916E-06, CFL  0.00294, SL -6.4127E-06, M 6.97073E+15, S 35.2427, T  6.2457, Me -7.46E-10, Se -6.81E-07, Te -6.81E-06
>     18,  731595.750,     0, En 1.2185516095946735E-05, CFL  0.00794, SL -9.2141E-06, M 6.97073E+15, S 35.2427, T  6.2459, Me -7.00E-10, Se -9.89E-07, Te -1.00E-05
>     24,  731596.000,     0, En 2.4391883408641453E-05, CFL  0.00870, SL -1.3774E-05, M 6.97073E+15, S 35.2427, T  6.2457, Me -1.14E-09, Se -1.40E-06, Te -1.42E-05
>     30,  731596.250,     0, En 2.9283640487163710E-05, CFL  0.00724, SL -1.8458E-05, M 6.97073E+15, S 35.2427, T  6.2454, Me -1.17E-09, Se -1.93E-06, Te -1.96E-05
>     36,  731596.500,     0, En 3.6652617800868474E-05, CFL  0.00746, SL -2.3211E-05, M 6.97073E+15, S 35.2427, T  6.2451, Me -1.19E-09, Se -2.37E-06, Te -2.42E-05
>     42,  731596.750,     0, En 4.2253748371831278E-05, CFL  0.00812, SL -2.7653E-05, M 6.97073E+15, S 35.2427, T  6.2454, Me -1.11E-09, Se -2.79E-06, Te -2.86E-05
>     48,  731597.000,     0, En 4.7781350107303387E-05, CFL  0.00941, SL -3.1143E-05, M 6.97073E+15, S 35.2427, T  6.2453, Me -8.73E-10, Se -3.05E-06, Te -3.14E-05
> ```

Thank you @yichengt900. Can you point me to where I can find such information for future PRs? If I can locate it, it might make things easier for you!

**Comment by yichengt900** [comment]
@charliestock, @feida6996, below are the 10-year (1993-2002) average model surface ALK, DIC, and Omega from the NWA12 domain with @feida6996's new default values for `ca_2_n_arag` and `ca_2_n_calc`. In general, they look okay to me. I will approve this PR now, but let me know if either of you have any further concerns.

1993-2007 avg model surface ALK, DIC and Omega with org parameters:
alk_dic_omega

1993-2007 avg model surface ALK, DIC and Omega with new parameters:
alk_dic_omega

Th surface ALK/DIC is slightly lower with the new parameters.

**Review by yichengt900 — APPROVED** [review]
The PR changes the default values of `ca_2_n_arag` and `ca_2_n_calc` based on the recent recalibration of calcite and aragonite detritus flux from the global-scale experiment. After recalibration, we achieved the targeted PIC flux of 0.9 Pg C y-1 at a depth of 100 m, with a calcite and aragonite flux ratio of approximately 3:1.

**Pull request merged**
